name: 'cron'

on:
  schedule:
  - cron: '*/10 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the docker image
      run: docker build --no-cache=true -t ${{ github.repository }}:${{ github.sha }} .
    - name: Run the docker image
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        GO111MODULE: on
      with:
        IMAGE: ${{ github.repository }}
        TAG: ${{ GITHUB_SHA::8 }}
      run: docker run $IMAGE:$TAG
