name: 'cron'

on:
  schedule:
  - cron: '*/5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --no-cache=true -t ${{ github.repository }}:${{ github.sha }} .
    - name: Run the image
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        GO111MODULE: on
      run: docker run -it ${{ github.repository }}:${{ github.sha }}
