name: 'cron'

on:
  schedule:
  - cron: '0 */1 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build --no-cache=true -t ${{ github.repository }}:${{ github.sha }} .
    - name: Run the image
      run: docker run -it -e CONSUMER_KEY=${{ secrets.CONSUMER_KEY }} \
        -e CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }} \
        -e ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} \
        -e ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} \
        -e GO111MODULE=on \
        ${{ github.repository }}:${{ github.sha }}
